services:
  pgsql:
    image: postgres:13
    hostname: database
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgsql:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nextcloud
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "nextcloud" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  nextcloud:
    image: nextcloud:30
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - .:/var/www/html/custom_apps/nextmail:z
      - nextcloud:/var/www/html:Z
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    depends_on:
      pgsql:
        condition: service_healthy

  stalwart:
    image: stalwartlabs/mail-server:v0.10.3
    hostname: stalwart
    ports:
      - "127.0.0.1:9090:8080"
    volumes:
      - stalwart:/opt/stalwart-mail:Z
    depends_on:
      pgsql:
        condition: service_healthy

networks:
  default:

volumes:
  nextcloud:
  pgsql:
  stalwart:
