services:
  mysql:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1

  nextcloud:
    image: nextcloud:apache
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - .:/var/www/html/custom_apps/stalwart:Z
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    depends_on:
      - mysql
      - stalwart

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:8989:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql

  stalwart:
    image: stalwartlabs/mail-server:latest
    hostname: stalwart
    ports:
      - "127.0.0.1:9090:8080"
    volumes:
      - stalwart:/opt/stalwart:Z

networks:
    default:

volumes:
  nextcloud:
  mysql:
  stalwart:
