services:
  mysql:
    image: mariadb:10.6
    hostname: database
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  nextcloud_init:
    image: nextcloud:30
    command: apache2 -v
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=database
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    depends_on:
      mysql:
        condition: service_healthy

  nextcloud:
    image: nextcloud:30
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - .:/var/www/html/custom_apps/stalwart:z
      - nextcloud:/var/www/html:z
    environment:
      - MYSQL_HOST=database
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    depends_on:
      mysql:
        condition: service_healthy
      nextcloud_init:
        condition: service_completed_successfully

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "127.0.0.1:8989:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy

  stalwart:
    image: stalwartlabs/mail-server:v0.10.3
    hostname: stalwart
    ports:
      - "127.0.0.1:9090:8080"
    volumes:
      - stalwart:/opt/stalwart:z
    depends_on:
      mysql:
        condition: service_healthy

networks:
    default:

volumes:
  nextcloud:
  mysql:
  stalwart:
